package co.edu.uniajc.cajero.model;
// Generated 25-mar-2019 9:45:11 by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name = "cuenta")
public class Cuenta implements java.io.Serializable {

	private Integer idCuenta;
	private Banco banco;
	private Estado estado;
	private Producto producto;
	private Usuario usuario;
	private String numero;
	private BigDecimal saldo;
	private String clave;
	private Set detalles = new HashSet(0);
	private Set tarjetas = new HashSet(0);

	public Cuenta() {
	}

	public Cuenta(Banco banco, Estado estado, Producto producto, Usuario usuario, String numero, BigDecimal saldo,
			String clave) {
		this.banco = banco;
		this.estado = estado;
		this.producto = producto;
		this.usuario = usuario;
		this.numero = numero;
		this.saldo = saldo;
		this.clave = clave;
	}

	public Cuenta(Banco banco, Estado estado, Producto producto, Usuario usuario, String numero, BigDecimal saldo,
			String clave, Set detalles, Set tarjetas) {
		this.banco = banco;
		this.estado = estado;
		this.producto = producto;
		this.usuario = usuario;
		this.numero = numero;
		this.saldo = saldo;
		this.clave = clave;
		this.detalles = detalles;
		this.tarjetas = tarjetas;
	}

	public Integer getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public Set getDetalles() {
		return this.detalles;
	}

	public void setDetalles(Set detalles) {
		this.detalles = detalles;
	}

	public Set getTarjetas() {
		return this.tarjetas;
	}

	public void setTarjetas(Set tarjetas) {
		this.tarjetas = tarjetas;
	}

}
