package co.edu.uniajc.cajero.model;
// Generated 25-mar-2019 9:45:11 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Movimiento generated by hbm2java
 */

@Entity
@Table(name = "movimiento")
public class Movimiento implements java.io.Serializable {

	private Integer idMovimiento;
	private String descripcion;
	private Set detalles = new HashSet(0);

	public Movimiento() {
	}

	public Movimiento(String descripcion, Set detalles) {
		this.descripcion = descripcion;
		this.detalles = detalles;
	}

	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getDetalles() {
		return this.detalles;
	}

	public void setDetalles(Set detalles) {
		this.detalles = detalles;
	}

}
