package co.edu.uniajc.cajero.model;
// Generated 25-mar-2019 9:45:11 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto")
public class Producto implements java.io.Serializable {

	private Integer idProducto;
	private String descripcion;
	private Set cuentas = new HashSet(0);

	public Producto() {
	}

	public Producto(String descripcion) {
		this.descripcion = descripcion;
	}

	public Producto(String descripcion, Set cuentas) {
		this.descripcion = descripcion;
		this.cuentas = cuentas;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
