package co.edu.uniajc.CajeroAutomatico.model;
// Generated 7/04/2019 12:54:01 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento implements java.io.Serializable {

	private Integer idMovimiento;
	private String descripcion;
	private Set detalles = new HashSet(0);

	public Movimiento() {
	}

	public Movimiento(String descripcion, Set detalles) {
		this.descripcion = descripcion;
		this.detalles = detalles;
	}

	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getDetalles() {
		return this.detalles;
	}

	public void setDetalles(Set detalles) {
		this.detalles = detalles;
	}

}
