package co.edu.uniajc.CajeroAutomatico.model;
// Generated 7/04/2019 12:54:01 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer idProducto;
	private String descripcion;
	private Set cuentas = new HashSet(0);

	public Producto() {
	}

	public Producto(String descripcion) {
		this.descripcion = descripcion;
	}

	public Producto(String descripcion, Set cuentas) {
		this.descripcion = descripcion;
		this.cuentas = cuentas;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
