package co.edu.uniajc.CajeroAutomatico.model;
// Generated 7/04/2019 12:54:01 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TipoIdentificacion generated by hbm2java
 */
public class TipoIdentificacion implements java.io.Serializable {

	private Integer idIdentificacion;
	private String descripcion;
	private Set usuarios = new HashSet(0);

	public TipoIdentificacion() {
	}

	public TipoIdentificacion(String descripcion, Set usuarios) {
		this.descripcion = descripcion;
		this.usuarios = usuarios;
	}

	public Integer getIdIdentificacion() {
		return this.idIdentificacion;
	}

	public void setIdIdentificacion(Integer idIdentificacion) {
		this.idIdentificacion = idIdentificacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
